# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site.

# Basic Site Settings
locale                   : "en-US"
title                    : "Jaewoo Lee"
title_separator          : "-"
name                     : &name "Jaewoo Lee"
description              : &description "Personal academic website of Jaewoo Lee, Ph.D. Candidate in Management Science at the Darla Moore School of Business, University of South Carolina."
url                      : "https://l3114987.github.io"
baseurl                  : ""
repository               : "l3114987/l3114987.github.io"

# Site Author - The following controls what appears as part of the author profile on the sidebar.
author:
  # Biographic information
  avatar            : "/images/Profile_jaewoo.jpg"
  name              : "Jaewoo Lee"
  pronouns          : "He/him/his"
  bio               : "Ph.D. Candidate in Management Science, Darla Moore School of Business, University of South Carolina"
  location          : "Columbia, SC"
  employer          : "University of South Carolina"
  uri               : "https://l3114987.github.io"
  email             : "jaewoo.lee@grad.moore.sc.edu" 

  # Academic websites
  arxiv             : # URL
  googlescholar     : "" # 구글 스칼라 프로필 생성 시 URL 입력
  impactstory       : # URL
  orcid             : "" # ORCID 생성 시 ID 입력
  semantic          : # URL
  pubmed            : # URL
  researchgate      : # URL

  # Repositories and software development
  bitbucket         : 
  codepen           : 
  dribbble          : 
  github            : "l3114987"
  kaggle            : 
  stackoverflow     : 

  # Social media
  bluesky           : 
  facebook          : 
  flickr            : 
  foursquare        : 
  goodreads         : 
  google_plus       : 
  keybase           : 
  instagram         : 
  lastfm            : 
  linkedin          : "jaewoo-lee-947859157"
  mastodon          : 
  medium            : 
  pinterest         : 
  soundcloud        : 
  steam             : 
  telegram          : 
  tumblr            : 
  twitter           : 
  vine              : 
  weibo             : 
  wikipedia         : 
  xing              : 
  youtube           : 
  zhihu             : 

# Teaser & Defaults
teaser                   : 
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false

# Comments
comments:
  provider               : false

atom_feed:
  hide                   : false
  path                   : 

# SEO & Analytics
analytics:
  provider               : "false"

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Markdown Processing
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: America/New_York

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development
